### ISSUE TITLE
finch sample won't compile

### ISSUE THREAD

**Issue by mfirry** [avibryant/bazel-scala-example#3]
Hi,
I tried out bazel with a sample app that uses [finch](https://github.com/finagle/finch) but for some reason I can't get it to compile.

Here it is https://github.com/mfirry/finch-finch.

Compilation error is `finch/src/main/scala/WebServer.scala:25: error: could not find implicit value for parameter tr: io.finch.internal.ToResponse.Aux[WebServer.Message,io.finch.Application.Json]
    Http.serve("localhost:9000", json.toService)`

So it's like it's missing some `implicit` coming from, I guess, `finch-circe`.

What am I doing wrong?

Thanks.

**Comment by johnynek** [comment]
you need the transitive dependencies set up. I don't see them in your git repo (`3rdparty/jvm` is empty, which is where we normally put them).

Then your code needs to depend on the finch-circe build target. Since macros are used, you'll probably have to `export: ["group:artifact"]` on some of the circe targets.

**Comment by mfirry** [comment]
I gitignored (neologism!) that folder. Shouldn't I?

**Comment by johnynek** [comment]
We don't since we don't want to re-run the resolving process of bazel-deps on every build.

By default, it does not export all the transitive dependencies as compile time dependencies. For circe we have:

```
  io.circe:
    circe:
      version: "0.5.0-M2"
      lang: scala
      modules: [core, generic, parser, jawn, numbers]
    circe-generic:
      version: "0.5.0-M2"
      lang: scala
      exports: # due to the macros, these need to be here at compile time
        - "com.chuusai:shapeless"
        - "io.circe:circe-core"
        - "org.typelevel:cats-core"
        - "org.typelevel:cats-kernel"
```

since circe actually has a number of compile time dependencies (some due to macros).

You can "fix" this by making the transitivity setting "exports". See the README:
https://github.com/johnynek/bazel-deps
